name: Deploy to Production

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Verify SSH connection
      run: |
        echo "Testing connection to ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}"
        ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful!'; ls -ld ${{ secrets.TARGET_DIR }}"

    - name: Deploy files via Rsync
      run: |
        echo "Starting deployment to ${{ secrets.TARGET_DIR }}"
        rsync -avz --delete --progress \
          --exclude='.git/' \
          --exclude='.github/' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/
        
        echo "Verifying deployment"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "ls -la ${{ secrets.TARGET_DIR }} | head -n 5"