name: Deploy to Server2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_timeout: 15m
          ssh_verbose: true  # Включить подробное логирование
          script: |
            echo "=== Успешное подключение ==="
            whoami
            pwd
            ls -la /var/www/html
            echo "=== Завершено ==="